nota1 = float(input("Informe a primeira nota:\n"))
nota2 = float(input("Informe a segunda nota:\n"))
nota3 = float(input("Informe a terceira nota:\n"))
nota4 = float(input("Informe a quarta nota:\n"))
print(f"Nota 1: {nota1} \nNota 2: {nota2} \nNota 3: {nota3} \nNota 4: {nota4} \nMédia das notas: {(nota1 + nota2 + nota3 + nota4) / 4}")